export const MobileSetting = {
    // MAIN SETTINGS

    REVENGE: 'REVENGE',
    REVENGE_PLUGINS: 'REVENGE_PLUGINS',
    REVENGE_THEMES: 'REVENGE_THEMES',
    REVENGE_FONTS: 'REVENGE_FONTS',
    REVENGE_DEVELOPER: 'REVENGE_DEVELOPER',

    // SUBSETTINGS

    REVENGE_VERSION: 'REVENGE_VERSION',
    REACT_VERSION: 'REACT_VERSION',
    REACT_NATIVE_VERSION: 'REACT_NATIVE_VERSION',
    HERMES_VERSION: 'HERMES_VERSION',

    EVALUATE_JAVASCRIPT: 'EVALUATE_JAVASCRIPT',

    REVENGE_NOT_IMPLEMENTED: 'REVENGE_NOT_IMPLEMENTED',
} as const

export const UserSettingsSections = {
    [MobileSetting.REVENGE]: 'Revenge',
    [MobileSetting.REVENGE_PLUGINS]: 'Revenge Plugins',
    [MobileSetting.REVENGE_THEMES]: 'Revenge Themes',
    [MobileSetting.REVENGE_FONTS]: 'Revenge Fonts',
    [MobileSetting.REVENGE_DEVELOPER]: 'Revenge Developer',
} as const
