export const MobileSetting = {
    // MAIN SETTINGS

    REVENGE_DEVELOPER: 'REVENGE_DEVELOPER',

    // SUBSETTINGS

    REACT_DEVTOOLS_VERSION: 'REACT_DEVTOOLS_VERSION',
    REACT_DEVTOOLS_CONNECT: 'REACT_DEVTOOLS_CONNECT',
    REACT_DEVTOOLS_DISCONNECT: 'REACT_DEVTOOLS_DISCONNECT',
    EVALUATE_JAVASCRIPT: 'EVALUATE_JAVASCRIPT',
} as const

export const UserSettingsSections = {
    [MobileSetting.REVENGE_DEVELOPER]: 'Revenge Developer',
} as const
